### ISSUE TITLE
A typo in the README.md of case 2

### ISSUE THREAD

**Issue by BobAnkh** [TranSys2020/TranSys#3]
In the part of **Lightweight Deployment** of **case 2**, under the subtitle Lightweightified Implementations, the URL to visit is misspelled.
![image](https://user-images.githubusercontent.com/44333669/71969614-fc935b00-3241-11ea-9461-fdd90ce90adb.png)
It should be corrected to _http://localhost/index_XX.html_

The 4th line of the codes under the subtitle Prerequisites could be replaced by `grunt --force`

**Comment by TranSys2020** [comment]
Thank you for your suggestions! The readme is now fixed.
